version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    ports:
      - "3001:3001"
    networks:
      - network

  frontend:
    build:
      context: ./frontend-next
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend-next:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - network

networks:
    network:
      driver: bridge