version: "3.8"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    networks:
      - network

  frontend:
    build: ./frontend-next
    ports:
      - "80:80"
      - "443:443"
    networks:
      - network

networks:
  network:
    driver: bridge