version: "3.8"

services:
  backend:
    build: ./vite/backend
    networks:
      - network

  frontend:
    build: ./vite/frontend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - network

networks:
  network:
    driver: bridge