version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    networks:
      - network

  frontend:
    build:
      context: ./frontend-vite
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    networks:
      - network

networks:
    network:
      driver: bridge