version: "3.8"

services:
  backend:
    build: ./backend
    networks:
      - network

  frontend:
    build: ./frontend-vite
    ports:
      - "80:80"
      - "443:443"
    networks:
      - network

networks:
  network:
    driver: bridge