version: "3.8"

services:
  backend:
    build:
      context: ./vite/backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    ports:
      - "3001:3001"
    networks:
      - network

  frontend:
    build:
      context: ./vite/frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./vite/frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - network

networks:
    network:
      driver: bridge