version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app  # Mount the backend source directory to /app in the container
    networks:
      - network

  frontend:
    build:
      context: ./frontend-next
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    networks:
      - network

networks:
    network:
      driver: bridge