# pull official base image
FROM --platform=linux/amd64 node:lts-alpine3.19

# set working directory
WORKDIR /app

# install app dependencies
COPY package.json ./
RUN npm install --silent

# add app
COPY . ./

# Expose port 3000 to access the server
EXPOSE 3000

# start app
CMD ["npm", "run", "dev"]
