# pull official base image
FROM --platform=linux/amd64 node:13.12.0-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install --silent

# add app
COPY . ./

# Expose port 3000 to access the server
EXPOSE 3000

# start app
CMD ["npm", "run", "dev"]
